export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_RECEIVE = "LOGOUT_RECEIVE"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST" 
export const GET_PRODUCTS_RECEIVE = "GET_PRODUCTS_RECEIVE" 
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR" 

export const ADD_PRODUCT_TO_ORDER_REQUEST = "ADD_PRODUCT_TO_ORDER_REQUEST"
export const ADD_PRODUCT_TO_ORDER_RECEIVE = "ADD_PRODUCT_TO_ORDER_RECEIVE"
export const ADD_PRODUCT_TO_ORDER_ERROR = "ADD_PRODUCT_TO_ORDER_ERROR"

export const DELETE_PRODUCT_FROM_ORDER_REQUEST = "DELETE_PRODUCT_FROM_ORDER_REQUEST"
export const DELETE_PRODUCT_FROM_ORDER_RECEIVE = "DELETE_PRODUCT_FROM_ORDER_RECEIVE"
export const DELETE_PRODUCT_FROM_ORDER_ERROR = "DELETE_PRODUCT_FROM_ORDER_ERROR"

export const CHANGE_COUNT_PRODUCT_INTO_ORDER_REQUEST = "CHANGE_COUNT_PRODUCT_INTO_ORDER_REQUEST"
export const CHANGE_COUNT_PRODUCT_INTO_ORDER_RECEIVE = "CHANGE_COUNT_PRODUCT_INTO_ORDER_RECEIVE"
export const CHANGE_COUNT_PRODUCT_INTO_ORDER_ERROR = "CHANGE_COUNT_PRODUCT_INTO_ORDER_ERROR"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_RECEIVE = "GET_ORDER_RECEIVE"
export const GET_ORDER_ERROR = "GET_ORDER_ERROR" 

export const CLEAN_ORDER = "CLEAN_ORDER" 

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_RECEIVE = "CANCEL_ORDER_RECEIVE"
export const CANCEL_ORDER_ERROR = "CANCEL_ORDER_ERROR"

export const SUBMIT_ORDER_REQUEST = "SUBMIT_ORDER_REQUEST"
export const SUBMIT_ORDER_RECEIVE = "SUBMIT_ORDER_RECEIVE"
export const SUBMIT_ORDER_ERROR = "SUBMIT_ORDER_ERROR"

